### ISSUE TITLE
Default settings for labels

### ISSUE THREAD

**Issue by loekderooij** [redjepakketje/magento-shipping#2]
Please add more default settings in the config.xml file. At least for settings using a source model that does not support an empty value. The default label settings seemed fine for us, but were actually empty since they do not have a default value. This cause the API call creating a shipment to pass get parameter `label=` instead of `label=pdf`. No label was returned in the response a  consequence and the tracking codes and label were not visible in Magento admin.

**Comment by arjanvdbos** [comment]
Thanks @loekderooij for reporting this issue! I just created a fix with PR #3. Will test and merge it later.
